name : ma premiere pipeline
on : 
  push :
    branches :
      - main
      - momo/pipeline

jobs :
  Hello-world :
    runs-on : ubuntu-latest

    steps :
      - name : Dîtes bonjour
        run : echo "Hello, World ^^"
  
  Hello-space :
    runs-on : ubuntu-latest

    steps :
      - name : Dîtes Nasa
        run : echo "L'homme n'a jamais mit le pied sur la Lune"