name : ma premiere pipeline
on : 
  push :
    branches :
      - main
      - momo/pipeline

jobs :
  Hello-world :
    runs-on : ubuntu-latest

    steps :
      - name: Checkout code
        uses: actions/checkout@v3
      - name : Dîtes bonjour
        run : |
          echo "Hello, World ^^"
          echo "Hello, les poeple"
  
  Hello-space :
    runs-on : ubuntu-latest

    steps :
      - name: Checkout code
        uses: actions/checkout@v3
      - name : Dîtes Nasa
        run : echo "L'homme n'a jamais mit le pied sur la Lune"

  Hello-python :
    runs-on : ubuntu-latest

    steps :
      - name: Checkout code
        uses: actions/checkout@v3
      - name : ls
        run : ls
      - name : Dîtes python
        run : |
          ls
          python3 print_hello.py
  
  Hello-python-docker :
    runs-on : ubuntu-latest

    steps :
      - name: Checkout code
        uses: actions/checkout@v3
      - name : Run hello python docker
        run : |
          docker run mderbane/python-app:latest

  Hello-python-docker-build :
    runs-on : ubuntu-latest

    steps :
      - name: Checkout code
        uses: actions/checkout@v3
      - name : build docker
        run : |
          docker build -t mderbane/python-app:latest .
      - name : Run hello python docker
        run : |
          docker run mderbane/python-app:latest